#!/usr/bin/env bash
#
# sync-skills.sh — vendor external skill providers into this marketplace.
#
# Reads scripts/skill-sources.json and mirrors a curated set of upstream skills
# into skills/vendor/<provider>/<name>/, then registers them in plugin.json's
# `skills` array (which EXTENDS the default skills/ scan — hand-authored skills
# keep loading untouched). The vendor tree is fully regenerated each run, so
# skills removed upstream or dropped from include_categories are pruned.
#
# Mutates the working tree only — it never commits, pushes, or opens PRs. Run it
# locally and review `git diff`; in CI the sync-skills workflow handles git + PR.
#
# Portable on purpose: POSIX find/grep/sed and bash 3.2 features only (this runs
# on CI ubuntu AND macOS's stock bash), so no `fd`/`rg`/mapfile/`declare -A`.
#
# Usage: bash scripts/sync-skills.sh

set -euo pipefail
shopt -s nullglob

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
CONFIG="scripts/skill-sources.json"

for tool in jq git; do
  command -v "$tool" >/dev/null 2>&1 || { echo "sync-skills: '$tool' is required" >&2; exit 1; }
done
[ -f "$CONFIG" ] || { echo "sync-skills: missing $CONFIG" >&2; exit 1; }
[ -f "plugin.json" ] || { echo "sync-skills: run from a checkout with plugin.json" >&2; exit 1; }

# Frontmatter `name:` of a SKILL.md (the actual invocation name for skills loaded
# via an explicit plugin.json `skills` path); falls back to the dir basename.
fm_name() {
  awk -F':[[:space:]]*' '/^name:/{print $2; exit}' "$1" 2>/dev/null \
    | tr -d "\"' " | tr -d '[:space:]'
}

# Local hand-authored skill command names = basenames of top-level skills/*/,
# excluding the vendor tree. These are claimed; we never overwrite them.
taken=""
for d in skills/*/; do
  b="$(basename "$d")"
  [ "$b" = "vendor" ] && continue
  taken="$taken $b"
done

tmproot="$(mktemp -d)"
trap 'rm -rf "$tmproot"' EXIT

vendor_paths=""   # ./skills/vendor/<provider>/<name> entries for plugin.json

nprov="$(jq '.providers | length' "$CONFIG")"
pi=0
while [ "$pi" -lt "$nprov" ]; do
  prov="$(jq -c ".providers[$pi]" "$CONFIG")"
  pi=$((pi + 1))

  name="$(printf '%s' "$prov" | jq -r '.name')"
  repo="$(printf '%s' "$prov" | jq -r '.repo')"
  ref="$(printf '%s' "$prov" | jq -r '.ref')"
  license="$(printf '%s' "$prov" | jq -r '.license // "see upstream"')"
  dest="$(printf '%s' "$prov" | jq -r '.dest')"

  echo "==> $name  ($repo@$ref)"
  clone="$tmproot/$name"
  git clone --quiet --depth 1 --branch "$ref" "https://github.com/$repo" "$clone"
  sha="$(git -C "$clone" rev-parse HEAD)"
  cdate="$(git -C "$clone" log -1 --format=%cI)"

  # Full mirror: wipe and rebuild this provider's vendor dir from scratch.
  rm -rf "$dest"
  mkdir -p "$dest"

  included=""   # "category/skname" entries vendored for this provider
  ncat="$(printf '%s' "$prov" | jq -r '.include_categories | length')"
  ci=0
  while [ "$ci" -lt "$ncat" ]; do
    cat="$(printf '%s' "$prov" | jq -r ".include_categories[$ci]")"
    ci=$((ci + 1))
    catdir="$clone/skills/$cat"
    [ -d "$catdir" ] || { echo "  ! category not found upstream: $cat" >&2; continue; }

    for sk in "$catdir"/*/; do
      sk="${sk%/}"
      [ -f "$sk/SKILL.md" ] || continue
      skname="$(basename "$sk")"

      if printf '%s' "$prov" | jq -e --arg s "$skname" '(.exclude_skills // []) | index($s)' >/dev/null; then
        echo "  - excluded: $skname"
        continue
      fi

      # Collision guard on the EFFECTIVE command name (frontmatter name).
      cmd="$(fm_name "$sk/SKILL.md")"
      [ -n "$cmd" ] || cmd="$skname"
      case " $taken " in
        *" $cmd "*) echo "  ! SKIPPED (collision): $cmd  (from $cat/$skname)" >&2; continue ;;
      esac

      cp -Rp "$sk" "$dest/"          # -> $dest/$skname (preserves scripts/, *.md, modes)
      taken="$taken $cmd"
      included="$included $cat/$skname"
      vendor_paths="$vendor_paths ./$dest/$skname"
      echo "  + $cat/$skname"
    done
  done

  # Attribution: keep upstream LICENSE + a provenance README in the vendor dir.
  [ -f "$clone/LICENSE" ] && cp "$clone/LICENSE" "$dest/LICENSE"
  {
    echo "# Vendored skills — $name"
    echo
    echo "**GENERATED — do not hand-edit.** Regenerated by \`scripts/sync-skills.sh\` from"
    echo "\`scripts/skill-sources.json\`. Local changes will be overwritten on the next sync."
    echo
    echo "- Source: https://github.com/$repo (ref \`$ref\`)"
    echo "- Commit: \`$sha\`"
    echo "- Upstream commit date: $cdate"
    echo "- License: $license (see [LICENSE](./LICENSE))"
    echo
    echo "## Included skills"
    echo
    for s in $included; do
      echo "- \`${s##*/}\` — upstream \`skills/$s\`"
    done
  } > "$dest/README.md"
done

# Regenerate plugin.json `skills` (sorted, deduped). EXTENDS the default skills/
# scan, so hand-authored skills are intentionally NOT listed here.
skills_json="$(printf '%s\n' $vendor_paths | sort -u | jq -R . | jq -s 'map(select(length > 0))')"
tmp="$(mktemp)"
jq --argjson skills "$skills_json" '.skills = $skills' plugin.json > "$tmp" && mv "$tmp" plugin.json

count="$(printf '%s' "$skills_json" | jq 'length')"
echo
echo "Synced $count vendored skill(s). plugin.json .skills updated."
